MobileStoreFeatureFlags/Models/ErrorViewModel.cs
namespace MobileStoreFeatureFlags.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MobileStoreFeatureFlags/Models/Mobile.cs
namespace MobileStoreFeatureFlags.Models
{
    public class Mobile
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public string? Specification { get; set; }
        public MobileReview MobileReview { get; set; }
    }
}

MobileStoreFeatureFlags/Models/MobileReview.cs
namespace MobileStoreFeatureFlags.Models
{
    public class MobileReview
    {
        public string? Rating { set; get; }
        public string? Remarks { set; get; }
    }
}

MobileStoreFeatureFlags/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MobileStoreFeatureFlags.Models;
using System.Diagnostics;

namespace MobileStoreFeatureFlags.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MobileStoreFeatureFlags/Controllers/MobilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement;
using Microsoft.FeatureManagement.Mvc;
using MobileStoreFeatureFlags.Features;
using MobileStoreFeatureFlags.Models;
using MobileStoreFeatureFlags.Services;

namespace MobileStoreFeatureFlags.Controllers
{
    //[FeatureGate(nameof(FeatureFlags.MobileReview))]
    public class MobilesController : Controller
    {
        private readonly IMobileDataService _mobileDataService;
        private readonly IFeatureManager _featureManager;

        public MobilesController(IMobileDataService mobileDataService,
            IFeatureManager featureManager)
        {
            _mobileDataService = mobileDataService;
            _featureManager = featureManager;
        }

        public async Task<IActionResult> Index()
        {
            //THIS FEATURE FLAG IS ADDED IN FEATURE MANAGER in AZURE APP CONFIG as MobileDetailedReview
            if (await _featureManager.IsEnabledAsync(nameof(FeatureFlags.MobileDetailedReview)))
            {
                ViewBag.IsEnabled = "Viewing Mobile Details is enabled";
            }
            else
            {
                ViewBag.IsEnabled = "Viewing Mobile Details is not enabled";
            }

            List<Mobile> mobiles = _mobileDataService.GetAllMobiles();
            return View(mobiles);
        }

        [FeatureGate(nameof(FeatureFlags.MobileDetailedReview))]
        public IActionResult ReviewDetails(string? mobileId)
        {
            Mobile mobile = _mobileDataService.GetAllMobiles()
                .Find(p => p.Id.Equals(mobileId));

            return View(mobile);
        }
    }
}

MobileStoreFeatureFlags/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MobileStoreFeatureFlags/Views/Mobiles/Index.cshtml
@using MobileStoreFeatureFlags.Features
@model List<Mobile>
@{
    ViewData["Title"] = "View All Mobiles Review";
}

<h1>@ViewData["Title"]</h1>

<h6 class="text-danger" style="font-weight: bold">@ViewBag.IsEnabled</h6>

<table class="table table-responsive table-hover">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Specification</td>
        <td>Rating</td>
        <td>Review Details</td>
    </tr>
    @foreach (Mobile mobile in Model)
    {
        <tr>
            <td>@mobile.Id</td>
            <td>@mobile.Name</td>
            <td>@mobile.Specification</td>
            <td>@mobile.MobileReview.Rating</td>
            <td>@Html.ActionLink("Click Here", "ReviewDetails", new { mobileId = mobile.Id })</td>
        </tr>
    }
</table>

MobileStoreFeatureFlags/Views/Mobiles/ReviewDetails.cshtml
@model MobileStoreFeatureFlags.Models.Mobile
@{
    ViewData["Title"] = "Mobile Detailed Review";
}
<h1>@ViewData["Title"]</h1>

<br />

<div class="my-3">
    <a class="btn btn-primary" asp-controller="Mobiles" asp-action="Index">Back</a>
</div>

<table class="table table-responsive table-hover">
    <tr>
        <td><span style="font-weight:bold">Id</span></td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Name</span></td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Specifications</span></td>
        <td>@Model.Specification</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Rating</span></td>
        <td>@Model.MobileReview.Rating</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Review</span></td>
        <td>@Model.MobileReview.Remarks</td>
    </tr>
</table>

MobileStoreFeatureFlags/Views/Shared/_Layout.cshtml
@using MobileStoreFeatureFlags.Features
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MobileStoreFeatureFlags</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MobileStoreFeatureFlags.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MobileStoreFeatureFlags</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mobiles" asp-action="Index">Mobile Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MobileStoreFeatureFlags - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>